version: '2.3'

services:
  triton: 
    image: triton
    build: ./Triton 
    # image: intel_model_model
    stdin_open: true
    tty: true
    volumes:
      - ./Triton/models:/models
    ulimits:
      memlock: -1 # set upper limit for how much memory is locked for the container (-1 means lock as much as the container uses)
    shm_size: 16gb # set upper limit for how much shared memory container can use
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    command: tritonserver --model-repository=/models
    restart: always
